include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics

#Dart code metrics configs
dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 10
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - avoid-unused-parameters
    - no-empty-block
#    - prefer-trailing-comma:
#        break-on: 2
#    - member-ordering:
#        alphabetize: false
#        order:
#          - constructors
#          - public-fields
#          - getters-setters
#          - private-fields
#          - public-methods
#          - private-methods
#          - public-static-methods
#          - private-static-methods

#    - newline-before-return
#    - no-boolean-literal-compare
#    - prefer-conditional-expressions
#    - no-equal-then-else
#    - no-magic-number

#Flutter lints configs
linter:
  rules:
    omit_local_variable_types: false
    avoid_dynamic_calls: true
    #await_only_futures: true

    always_declare_return_types: true
    prefer_single_quotes: true
    use_full_hex_values_for_flutter_colors: true
    sort_child_properties_last: true
    unawaited_futures: true
    unsafe_html: true
