include: package:flutter_lints/flutter.yaml

linter:
  rules:
    omit_local_variable_types: false
    avoid_dynamic_calls: true
    #await_only_futures: true

    always_declare_return_types: true
    prefer_single_quotes: true
    use_full_hex_values_for_flutter_colors: true
    sort_child_properties_last: true
    unawaited_futures: true
    unsafe_html: true
